AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  GetWoeid:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      CodeUri: ./code
      Timeout: 300
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
